# Generated by Django 5.2.15 on 2026-06-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateField(verbose_name='Дата оприбуткування')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Номер документа')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Створено користувачем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Накладна оприбуткування',
                'verbose_name_plural': 'Накладні оприбуткування',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('type', models.CharField(choices=[('warehouse', 'Склад'), ('showroom', 'Шоурум')], default='warehouse', max_length=20, verbose_name='Тип')),
                ('address', models.TextField(blank=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склади',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товару')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Собівартість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsreceiptnote', verbose_name='Накладна')),
            ],
            options={
                'verbose_name': 'Позиція накладної',
                'verbose_name_plural': 'Позиції накладних',
            },
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='inventory.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='goodsreceiptnote',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='inventory.warehouse', verbose_name='Склад'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товару')),
                ('quantity', models.IntegerField(verbose_name='Кількість')),
                ('type', models.CharField(choices=[('receipt', 'Оприбуткування'), ('transfer', 'Переміщення'), ('sale', 'Продаж'), ('adjustment', 'Коригування'), ('write_off', 'Списання'), ('reserve', 'Резервування'), ('release', 'Повернення резерву'), ('deduct', 'Списання залишку')], max_length=20, verbose_name='Тип')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Тип документа')),
                ('reference_id', models.CharField(blank=True, max_length=50, verbose_name='ID документа')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Створено користувачем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_from', to='inventory.warehouse', verbose_name='Зі складу')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements_to', to='inventory.warehouse', verbose_name='На склад')),
            ],
            options={
                'verbose_name': 'Рух товару',
                'verbose_name_plural': 'Рухи товару',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_id'], name='inventory_s_product_cbdc37_idx'), models.Index(fields=['type'], name='inventory_s_type_0df30a_idx'), models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товару')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість')),
                ('reserved', models.IntegerField(default=0, verbose_name='Зарезервовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Залишок',
                'verbose_name_plural': 'Залишки',
                'indexes': [models.Index(fields=['product_id'], name='inventory_s_product_4c1da7_idx'), models.Index(fields=['warehouse'], name='inventory_s_warehou_ecb923_idx')],
                'unique_together': {('product_id', 'warehouse')},
            },
        ),
    ]
