# Generated by Django 5.2.15 on 2026-06-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Середня собівартість'),
        ),
    ]
