# Generated by Django 5.2.15 on 2026-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_stockmovement_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('info', 'Info')], max_length=20, verbose_name='Тип події')),
                ('message', models.TextField(verbose_name='Повідомлення')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Тип сутності')),
                ('entity_id', models.CharField(blank=True, default='', max_length=50, verbose_name='ID сутності')),
                ('user_name', models.CharField(max_length=255, verbose_name="Ім'я користувача")),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email користувача')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Подія активності',
                'verbose_name_plural': 'Події активності',
                'ordering': ['-created_at'],
            },
        ),
    ]
