# Generated by Django 5.2.15 on 2026-06-20 09:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер замовлення')),
                ('channel', models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Офлайн (POS)')], default='online', max_length=20, verbose_name='Канал')),
                ('status', models.CharField(choices=[('pending', 'Очікує'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('warehouse_id', models.IntegerField(blank=True, null=True, verbose_name='ID складу виконання')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name="Ім'я покупця")),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон покупця')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email покупця')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Загальна сума')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='Створено користувачем')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'), models.Index(fields=['channel'], name='orders_orde_channel_491f77_idx'), models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx'), models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID товару')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Назва товару')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна продажу')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Собівартість')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлень',
            },
        ),
    ]
