# Generated by Django 5.2.15 on 2026-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_at_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Не сплачено'), ('paid', 'Сплачено'), ('delivering', 'В дорозі'), ('delivered', 'Доставлено'), ('completed', 'Виконано'), ('cancelled', 'Скасовано')], default='unpaid', max_length=20, verbose_name='Статус'),
        ),
    ]
