# Generated by Django 4.2.7 on 2025-11-29 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_sku_ca0cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_acti_ca4d9a_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AddField(
            model_name='product',
            name='originalPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Початкова ціна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=dict, verbose_name='Специфікації'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Поточна ціна'),
        ),
    ]
