# Generated by Django 5.2.8 on 2025-11-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_specs_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(default=[], verbose_name='Особливості'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(default={}, verbose_name='Специфікації'),
        ),
    ]
