# Generated by Django 5.2.8 on 2025-11-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_features_product_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='features',
            field=models.JSONField(default=list, verbose_name='Особливості'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=dict, verbose_name='Специфікації'),
        ),
    ]
