# Generated by Django 5.2.8 on 2026-06-11 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inStock',
            field=models.BooleanField(db_column='inStock', default=True, verbose_name='В наявності'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='inStock',
            new_name='in_stock',
        ),
        migrations.AlterField(
            model_name='product',
            name='originalPrice',
            field=models.DecimalField(db_column='originalPrice', decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Початкова ціна'),
        ),
        migrations.RenameField(
            model_name='product',
            old_name='originalPrice',
            new_name='original_price',
        ),
    ]
