# Generated by Django 5.2.15 on 2026-06-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name='ID події')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Оброблено')),
            ],
            options={
                'verbose_name': 'Оброблена подія',
                'verbose_name_plural': 'Оброблені події',
            },
        ),
    ]
