# Generated by Django 5.2.15 on 2026-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_processedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID сесії'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID користувача'),
        ),
    ]
