# Generated by Django 5.2.15 on 2026-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва (англ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(blank=True, max_length=100, verbose_name='Назва (укр)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Опис (англ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(blank=True, verbose_name='Опис (укр)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (англ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(blank=True, max_length=200, verbose_name='Назва (укр)'),
        ),
    ]
