# Generated by Django 5.2.15 on 2026-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_category_name_en_category_name_uk_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user_id__isnull', False)), fields=('user_id',), name='unique_user_cart'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_id__isnull', False)), fields=('session_id',), name='unique_session_cart'),
        ),
    ]
