# Generated by Django 5.1 on 2026-07-13

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    existing_slugs = set()
    for product in Product.objects.iterator():
        base = slugify(product.name_en or product.name or "") or f"product-{product.pk}"
        slug = base
        counter = 1
        while slug in existing_slugs:
            counter += 1
            slug = f"{base}-{counter}"
        product.slug = slug
        existing_slugs.add(slug)
        product.save(update_fields=['slug'])


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0017_cart_unique_user_cart_cart_unique_session_cart'),
    ]

    operations = [
        # Add as CharField first to avoid SlugField auto-index conflict
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL-ідентифікатор'),
            preserve_default=False,
        ),
        migrations.RunPython(generate_slugs, migrations.RunPython.noop),
        # Migrate to SlugField with unique + proper index
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-ідентифікатор'),
        ),
    ]
